/*
 * KGCL-Java - KGCL library for Java
 * Copyright © 2024 Damien Goutte-Gattat
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the Gnu General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.incenp.obofoundry.idrange;

/**
 * Represents an ID range policy, assigning ID ranges to users.
 */
public interface IIDRangePolicy {

    /**
     * Gets the prefix of IDs generated by this policy.
     * 
     * @return The prefix associated with this policy.
     */
    public String getPrefix();

    /**
     * Gets the short name of the policy's prefix.
     * 
     * @return The prefix name.
     */
    public String getPrefixName();

    /**
     * Gets the number of digits (padded with leading zeros) in the numerical part
     * of IDs generated with this policy.
     * 
     * @return The number of digits for this policy.
     */
    public int getWidth();

    /**
     * Gets the ID range allocated to the specified user.
     * 
     * @param name The name of the user for which to retrieve the ID range.
     * @return The range allocated to the user, or {@code null} if the policy has no
     *         range for that user.
     */
    public IDRange getRange(String name);
}
